#!/bin/bash


function stop_sys() {
	echo -n "Stopping GNUnet services (user 'gnunet'): "
	sudo su -s /bin/bash -c "/opt/gnunet/bin/gnunet-arm -c /etc/gnunet.conf -e" gnunet
	echo "done."
}

function stop_usr() {
	echo -n "Stopping GNUnet services (user 'user'): "
	/opt/gnunet/bin/gnunet-arm -c /home/user/.config/gnunet.conf -e
	echo "done."
}

case "$1" in
	sys)
		stop_sys
		;;
	usr)
		stop_usr
		;;
	all)
		stop_usr
		stop_sys
		;;
	*)
		echo "Unknown cmd '$1'... [sys,usr,all]"
		;;
esac
exit 0
