#!/bin/bash

# This file is part of gnunet-docker.
# Copyright (C) 2019-present, Bernd Fix  >Y<
#
# gnunet-docker is free software: you can redistribute it and/or modify it
# under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License,
# or (at your option) any later version.
#
# gnunet-docker is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# SPDX-License-Identifier: AGPL3.0-or-later


function stop_sys() {
	echo -n "Stopping GNUnet services (user 'gnunet'): "
	sudo su -s /bin/bash -c "/opt/gnunet/bin/gnunet-arm -c /etc/gnunet.conf -e" gnunet
	echo "done."
}

function stop_usr() {
	echo -n "Stopping GNUnet services (user 'user'): "
	/opt/gnunet/bin/gnunet-arm -c /home/user/.config/gnunet.conf -e
	echo "done."
}

case "$1" in
	sys)
		stop_sys
		;;
	usr)
		stop_usr
		;;
	all)
		stop_usr
		stop_sys
		;;
	*)
		echo "Unknown cmd '$1'... [sys,usr,all]"
		;;
esac
exit 0
