#!/bin/bash

function run_sys() {
	echo -n "Stopping GNUnet services (user 'gnunet'): "
	sudo su -s /bin/bash -c "/opt/gnunet/bin/gnunet-arm -c /etc/gnunet.conf -s" gnunet 2> /home/user/system.log
	echo "done."
}

function run_usr() {
	echo -n "Stopping GNUnet services (user 'user'): "
	/opt/gnunet/bin/gnunet-arm -c /home/user/.config/gnunet.conf -s 2> /home/user/user.log
	echo "done."
}

case "$1" in
	sys)
		run_sys
		;;
	usr)
		run_usr
		;;
	all)
		run_sys
		run_usr
		;;
	*)
		echo "Unknown cmd '$1'..."
		;;
esac
exit 0
