#!/bin/bash

# This file is part of gnunet-docker.
# Copyright (C) 2019-present, Bernd Fix  >Y<
#
# gnunet-docker is free software: you can redistribute it and/or modify it
# under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License,
# or (at your option) any later version.
#
# gnunet-docker is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# SPDX-License-Identifier: AGPL3.0-or-later

if [ -d $1 ]; then
	echo "Runtime directory '$1' exists -- aborting!"
	exit 1
fi

mkdir -p $1/{user,system}/.config
mkdir -p $1/{build,src}

cp gnunet-user.conf $1/user/.config/gnunet.conf
cat > $1/user/.bash_profile <<EOF
export PATH=/opt/gnunet/bin:\${PATH}
export NO_AT_BRIDGE=1
EOF
sudo chown -R 1000:1000 $1/{user,build,src}

cp gnunet-system.conf $1/system/.config/gnunet.conf
sudo chown -R 666:666 $1/system
