#!/bin/bash

# This file is part of gnunet-docker.
# Copyright (C) 2019-2022 Bernd Fix  >Y<
#
# gnunet-docker is free software: you can redistribute it and/or modify it
# under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License,
# or (at your option) any later version.
#
# gnunet-docker is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# SPDX-License-Identifier: AGPL3.0-or-later

export GNUNET_RUNTIME=${1:-/usr/local/gnunet/rt}

if [ ! -d ${GNUNET_RUNTIME}/user -a ! -d ${GNUNET_RUNTIME}/system ]; then
	echo "No valid runtime directory '${GNUNET_RUNTIME}'..."
	exit 1
fi

docker run --rm -ti --name gnunet-dev -h gnunet-dev \
	--cap-add=NET_ADMIN --cap-add=NET_BROADCAST --device=/dev/net/tun \
	-e DISPLAY=${DISPLAY} \
	-v /tmp/.X11-unix:/tmp/.X11-unix \
	-v ${GNUNET_RUNTIME}/user:/home/user \
	-v ${GNUNET_RUNTIME}/system:/var/lib/gnunet \
	-v ${GNUNET_RUNTIME}/build:/opt/gnunet \
	-v ${GNUNET_RUNTIME}/src:/opt/src \
	-p 0.0.0.0:2086:2086 \
	-p 0.0.0.0:1080:1080 \
	bfix/gnunet:dev
