#!/bin/bash

docker run --rm -ti --name gnunet -h gnunet \
	--cap-add=NET_ADMIN --cap-add=NET_BROADCAST --device=/dev/net/tun \
	-e DISPLAY=${DISPLAY} \
	-v /tmp/.X11-unix:/tmp/.X11-unix \
	-v /vault/security/gnunet/dev/user:/home/user \
	-v /vault/security/gnunet/dev/system:/var/lib/gnunet \
	-p 127.0.0.1:2086:2086 \
	-p 127.0.0.1:1080:1080 \
	bfix/gnunet

